### PR TITLE
Set up automated semantic release

### LINKED ISSUE #20: Set up automated semantic release

### PR DESCRIPTION
**Pull request by igorkamyshev**
Hello! Great lib. This PR add script for automated semantic release by `npm run release`. It uses https://github.com/conventional-changelog/standard-version for bumping version in package.json, creating CHANGELOG.md and adding git tag with created release.

fixes #20 

Please, review my PR and give me your feedback.

### CODE REVIEW

**Comment by fwoelffel** [comment]
Hi @igorkamyshev! Thanks for contributing and also for your feedback :smiley: I'm glad to hear that I haven't wasted my free time.

I know nothing about `soda` could you explain me why we should use this binary in place of [`standard-version`](https://github.com/conventional-changelog/standard-version) (which is the tool I had in mind for this task). It seems to me that `soda` is using `standard-version` under its hood.

**Comment by igorkamyshev** [comment]
@fwoelffel sure, @solid-soda/scripts just aggregate some packages in one place. For generating releases it uses `standard-version`.

I install it, because all of our packages includes boilerplate code, like `.prettierrc`, `tslint.json`, commit-lint config in package.json, etc.

I suggest soft migration to one package — @solid-soda/scripts for all this needs. But, I guess, now it is not so important task, we can do it later. Now I wanted simplify our future life.

If you think this is over-engineering, then I will replace this dependency by `standard-version`, of course. 😊

**Comment by igorkamyshev** [comment]
@fwoelffel what do you think?

**Comment by igorkamyshev** [comment]
@fwoelffel friendly ping 🙏

**Comment by fwoelffel** [comment]
Hi @igorkamyshev. There's no need to ping me as I make sure to check Github at least once a week :wink: 
I find your proposal a bit over-engineered and would prefer to stick with a vanilla `standard-version` call. Moreover, `soda` still looks pretty young and I'd like to avoid the integration of tools/library that are not yet battle-tested.

The purpose of this issue (#20) was also to discuss the release workflow and automation. Having a new scripts in the `package.json` is only one brick of this wall.

**Comment by igorkamyshev** [comment]
Yeah, you right!

I replace this custom solution by `standard-version`.

About automation, maybe we can use simple travis workflow? https://docs.travis-ci.com/user/deployment/npm/

**Comment by igorkamyshev** [comment]
@fwoelffel for setup automated releases by travis, you must execute command `travis stup npm` on you machine and pass NPM key to it. After that action, travis will release every tagged version (tag will be created by `yarn release`).

So, publishing process will be something like this:
```
yarn release
git push --follow-tags
```

**Comment by igorkamyshev** [comment]
@fwoelffel sorry. Don't you want to merge this PR, do you? Must I fix something? Please, give me instruction or just close this PR (it is okay 😊).

**Comment by fwoelffel** [comment]
Hi @igorkamyshev, I've updated the related issue to stimulate discussion around the subject of automated release. I've had a few experiences with automated release, and I'd like to get more insights from others before continuing with this.
This is only a nice-to-have feature and thus is not really a priority. I won't close this PR (unless you want to) since I still would like to set this up after the 1.0.0 release :)

**Comment by igorkamyshev** [comment]
@fwoelffel 👍

**Pull request closed without merging**
